from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io

def generate_resume_pdf(user_data):
    """
    User data se PDF generate karta hai aur BytesIO buffer return karta hai.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # --- Header Section (Blue Background) ---
    c.setFillColor(colors.darkblue)
    c.rect(0, height - 100, width, 100, fill=True, stroke=False)
    
    # Name & Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, user_data.full_name or "Full Name")
    
    c.setFont("Helvetica", 14)
    # Agar major hai to show karein, warna generic title
    title = user_data.major if user_data.major else "Scholarship Aspirant"
    c.drawString(50, height - 75, title)

    # --- Contact Info ---
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 10)
    contact_text = f"Email: {user_data.email} | Phone: {user_data.phone_number or 'N/A'}"
    c.drawString(50, height - 120, contact_text)
    
    c.drawString(50, height - 135, f"Location: {user_data.nationality or 'Global'}")

    # --- Section: Education ---
    y_position = height - 180
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.darkblue)
    c.drawString(50, y_position, "EDUCATION")
    c.line(50, y_position - 5, 200, y_position - 5) # Underline
    
    y_position -= 30
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.black)
    c.drawString(50, y_position, user_data.current_university or "University Name")
    
    y_position -= 15
    c.setFont("Helvetica", 11)
    degree_info = f"{user_data.current_degree or 'Degree'} in {user_data.major or 'Field'}"
    c.drawString(50, y_position, degree_info)
    
    y_position -= 15
    c.setFillColor(colors.gray)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y_position, f"Graduation: {user_data.graduation_year or 'N/A'} | CGPA: {user_data.cgpa or 'N/A'}")

    # --- Section: Future Goals ---
    y_position -= 50
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.darkblue)
    c.drawString(50, y_position, "SCHOLARSHIP GOALS")
    c.line(50, y_position - 5, 200, y_position - 5)

    y_position -= 30
    c.setFont("Helvetica", 11)
    c.setFillColor(colors.black)
    goal_text = f"Aspiring to pursue {user_data.target_degree or 'Degree'} in {user_data.target_country or 'Country'}."
    c.drawString(50, y_position, goal_text)

    # --- Footer ---
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.gray)
    c.drawCentredString(width / 2, 30, "Generated by ScholarIQ AI Resume Builder")

    c.save()
    buffer.seek(0)
    return buffer
